services:
  - type: web
    name: bnh-md
    env: node
    region: Frankfurt
    plan: free
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
        
