services:
  - type: web
    name: bnh-md
    env: node
    region: Frankfurt
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

